# Generated by Django 2.2 on 2020-10-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='hobby_image',
            field=models.CharField(default='https://www.dreamstime.com/kids-character-various-objects-flat-design-style-isolated-diversity-children-portrait-their-hobbies-vector-cartoon-image178264673', max_length=500),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_image',
            field=models.CharField(default='https://www.edmundsgovtech.com/wp-content/uploads/2020/01/default-picture_0_0.png', max_length=500),
        ),
    ]
